# docker
# alias dc='docker-compose'
# alias dcud='docker-compose up -d'
# alias dcu='docker-compose up'
# alias dcd='docker-compose down'
# alias dcre='docker-compose restart'
# alias dce='docker-compose exec'
# alias dcr='docker-compose run --rm'
# alias dcb='docker-compose build'

# git
alias g='git'
alias gcm='git commit -m'
alias gc='git commit'
alias gs='git status'
alias gst='git stash'
alias ga='git add'
alias gr='git reset'
alias gpl='git pull'
alias gcl='git clone'
alias gch='git checkout'
alias gp='git push'
alias gd='git diff'
alias gm='git merge'

# composer
alias c='composer'
alias cu='composer update'
alias csu='composer self-update'
alias ci='composer install'
alias cr='composer require'
